apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-team1
  namespace: namespace-team1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"